
FROM node:18-alpine AS build

WORKDIR /app

COPY Frontend/package.json Frontend/package-lock.json ./Frontend/
WORKDIR /app/Frontend

RUN npm install


COPY Frontend/. ./ 

RUN npm run build


FROM node:18-alpine

WORKDIR /app


RUN npm install -g serve


COPY --from=build /app/Frontend/dist ./dist



EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
